require:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety

AllCops:
  NewCops: enable

Layout/EndOfLine:
  EnforcedStyle: lf
Layout/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
