sudo: false
cache: bundler
language: ruby
rvm:
  - 3.0.0
  - 2.7
  - 2.6
before_install:
  - gem update --remote bundler
script:
  # - bundle exec rake
  - bundle exec rubocop --format simple --display-only-fail-level-offenses --fail-level W lib
deploy:
  provider: rubygems
  gem: fetch_and_process
  api_key:
    secure: pPFb3lu65isx+cZzbeoanz3qTnnr+7Ed05f1k8AazRlFTPmkkpQ+CQ1pUKOFglcJm6+dAw5cU0fRfeSJh0frGRlN4UhkJtjdNJq3BPMohpXBCG4rd7qrWOfRzHA99w84zVTjUpWCQ2FIfce/KrVDKPuqCFt1ENaE7azPW8YOnMy8qQ29PQisG/aXciIMTYFFqCopn1q/JKl6khWboRt1QjGHqdz3ihjSt1mRMG6ZeBu2t/o0h5IkgPHJo+/VKBbqBgtt6UPXF7FpA7eAyLddl41FD5E8NQjBjAL6tzC6jeaz5nfqa/LJOtVkB5HWTXxAvaPJJvR8H9VUSkhDrMmDJEKG6rg7wTQmiAOtI2r5t5XCOQMOA8my0dorFpokVOzQ8w5eFeTzJQM/BKdk3/tL2eJvoYGMvaP6/oG+8mzZkuC2ouqTx1/DSUSyu2Aal0pSsjvFUFEVAJc8J7pvTlhUVQaRW2Fhx4/HchsAePw5jsJolO5lybhwzE4l2XEPWVTjq8jq+QahqPoIBdsF4ws3daXUNGyC72jYGWHRNoEh1DFZu97SjwJMR2zSRma9ndRMsbHacJlNM/Mses6IaCsdTeY6HuNRctIhZs4CZSXiRICwqwjaTTL1+VafijSzM7GZZ6Q3+VKIfto5BheCzCwzU6byjYLEg+Oe+IyPwWMKXa8=
  on:
    tags: true
    repo: EagerELK/fetch_and_process
